In [2]:
import requests
import re
import tiktoken
import torch
from torch.utils.data import Dataset, DataLoader

In [3]:
url = "https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/main/ch02/01_main-chapter-code/the-verdict.txt"
response = requests.get(url)

if response.status_code == 200:
    with open("data/the-verdict.txt", "w") as file:
        file.write(response.text)
        print("File downloaded successfully.")
else:
    print("Failed to download the file.")


File downloaded successfully.


In [4]:
with open("data/the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()
    print("Total number of character:", len(raw_text))
    print(raw_text[:99])

Total number of character: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


## Tokenize
Naive approach based on regex

In [5]:
preprocessed = re.split(r'([,.?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(len(preprocessed))

4649


In [6]:
print(preprocessed[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


### Create vocabulary

In [7]:
all_words = sorted(list(set(preprocessed)))
vocab_size = len(all_words)
print(vocab_size)

1159


In [8]:
vocab = {token:integer for integer,token in enumerate(all_words)}
for i, item in enumerate(vocab.items()):
    print(item)
    if i > 50:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Carlo;', 25)
('Chicago', 26)
('Claude', 27)
('Come', 28)
('Croft', 29)
('Destroyed', 30)
('Devonshire', 31)
('Don', 32)
('Dubarry', 33)
('Emperors', 34)
('Florence', 35)
('For', 36)
('Gallery', 37)
('Gideon', 38)
('Gisburn', 39)
('Gisburns', 40)
('Grafton', 41)
('Greek', 42)
('Grindle', 43)
('Grindle:', 44)
('Grindles', 45)
('HAD', 46)
('Had', 47)
('Hang', 48)
('Has', 49)
('He', 50)
('Her', 51)


In [9]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        # Store the vocabulary as a class attribute for access in the encode and decode methods
        self.str_to_int = vocab
        # Create an inverse vocabulary that maps token IDs back to the original text tokens
        self.int_to_str = {i:s for s,i in vocab.items()}

    # Process input text into token IDs
    def encode(self, text):
        preprocessed = re.split(r'([,.?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if
        item.strip()]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    
    # Convert token IDs back into text
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuation
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [10]:
tokenizer = SimpleTokenizerV1(vocab)
text = """"It's the last he painted, you know," Mrs. Gisburn said with
pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

[1, 58, 2, 872, 1013, 615, 541, 763, 5, 1155, 608, 5, 1, 69, 7, 39, 873, 1136, 773, 812, 7]


In [11]:
tokenizer.decode(ids)

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

#### Handle unknown words

In [12]:
all_words.extend(["<|endoftext|>", "<|unk|>"])
vocab = {token:integer for integer,token in enumerate(all_words)}
print(len(vocab.items()))

1161


In [13]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        # Replace unknown words by <|unk|> tokens
        preprocessed = [item if item in self.str_to_int else "<|unk|>" for item in preprocessed]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [14]:
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = " <|endoftext|> ".join((text1, text2))
print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [15]:
tokenizer = SimpleTokenizerV2(vocab)
print(tokenizer.encode(text))

[1160, 5, 362, 1155, 642, 1000, 10, 1159, 57, 1013, 981, 1009, 738, 1013, 1160, 7]


In [16]:
print(tokenizer.decode(tokenizer.encode(text)))

<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.


### 

## Byte Pair Encoding (Tokenizer)

In [17]:
tokenizer = tiktoken.get_encoding("gpt2")

In [18]:
text = "Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownPlace."
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 286, 617, 34680, 27271, 13]


In [19]:
strings = tokenizer.decode(integers)
print(strings)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownPlace.


In [20]:
with open("data/the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [21]:
enc_sample = enc_text[50:]

### Create Next-Word Prediction Data

In [22]:
context_size = 4
x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]
print(f"x: {x}")
print(f"y: {y}")

x: [290, 4920, 2241, 287]
y: [4920, 2241, 287, 257]


In [23]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(context, "---->", desired)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


In [24]:
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.tokenizer = tokenizer
        self.input_ids = []
        self.target_ids = []
        # Tokenize the entire text
        token_ids = tokenizer.encode(txt)
        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    # Return the total number of rows in the dataset
    def __len__(self):
        return len(self.input_ids)
    
    # Return a single row from the dataset
    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [25]:
def create_dataloader(txt, batch_size=4, max_length=256, stride=128):
    tokenizer = tiktoken.get_encoding("gpt2") #A
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride) #B
    dataloader = DataLoader(dataset, batch_size=batch_size) #C
    return dataloader

In [26]:
with open("data/the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

dataloader = create_dataloader(raw_text, batch_size=1, max_length=4, stride=1)
data_iter = iter(dataloader) #A
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [27]:
dataloader = create_dataloader(raw_text, batch_size=8, max_length=4, stride=5)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 3619,   402,   271, 10899],
        [  257,  7026, 15632,   438],
        [  257,   922,  5891,  1576],
        [  568,   340,   373,   645],
        [ 5975,   284,   502,   284],
        [  326,    11,   287,   262],
        [  286,   465, 13476,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [  402,   271, 10899,  2138],
        [ 7026, 15632,   438,  2016],
        [  922,  5891,  1576,   438],
        [  340,   373,   645,  1049],
        [  284,   502,   284,  3285],
        [   11,   287,   262,  6001],
        [  465, 13476,    11,   339]])


In [28]:
input_ids = torch.tensor([5, 1, 3, 2])
vocab_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [29]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [30]:
print(embedding_layer(input_ids))

tensor([[-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010],
        [-0.4015,  0.9666, -1.1481],
        [ 1.2753, -0.2010, -0.1606]], grad_fn=<EmbeddingBackward0>)


## Create Full Training Data

In [31]:
output_dim = 256
vocab_size = 50257
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [32]:
max_length = 4
dataloader = create_dataloader(raw_text, batch_size=8, max_length=max_length, stride=5)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 3619,   402,   271, 10899],
        [  257,  7026, 15632,   438],
        [  257,   922,  5891,  1576],
        [  568,   340,   373,   645],
        [ 5975,   284,   502,   284],
        [  326,    11,   287,   262],
        [  286,   465, 13476,    11]])

Inputs shape:
 torch.Size([8, 4])


In [33]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [34]:
token_embeddings[0]

tensor([[ 0.4913,  1.1239,  1.4588,  ..., -0.3995, -1.8735, -0.1445],
        [ 0.4481,  0.2536, -0.2655,  ...,  0.4997, -1.1991, -1.1844],
        [-0.2507, -0.0546,  0.6687,  ...,  0.9618,  2.3737, -0.0528],
        [ 0.9457,  0.8657,  1.6191,  ..., -0.4544, -0.7460,  0.3483]],
       grad_fn=<SelectBackward0>)

In [35]:
block_size = max_length
pos_embedding_layer = torch.nn.Embedding(block_size, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(block_size))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [36]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])


In [37]:
input_embeddings[0]

tensor([[ 2.2288,  0.5619,  0.8286,  ..., -0.6272, -0.2987,  0.8900],
        [ 2.0903, -0.4664, -0.0593,  ...,  0.9115, -1.0493, -1.6473],
        [-0.7158, -0.8304,  1.2494,  ...,  2.3952,  1.8773,  0.8051],
        [ 0.2703,  0.4029,  3.0514,  ...,  0.3595, -1.4548,  0.8310]],
       grad_fn=<SelectBackward0>)

## End of Textbook Section
Below code not in book

In [68]:
print(torch.cuda.is_available())

True


In [77]:
import torch
import torch.nn as nn
import torch.optim as optim

# Check if CUDA is available and set
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

class GPT1(nn.Module):
    def __init__(self, vocab_size, output_dim, block_size, num_heads, num_layers):
        super().__init__()
        self.token_embedding_layer = nn.Embedding(vocab_size, output_dim)
        self.pos_embedding_layer = nn.Embedding(block_size, output_dim)
        self.transformer = nn.Transformer(output_dim, num_heads, num_layers, batch_first=True)
        self.linear = nn.Linear(output_dim, vocab_size)

    def forward(self, inputs):
        token_embeddings = self.token_embedding_layer(inputs)
        batch_size, seq_length, output_dim = token_embeddings.shape
        pos_embeddings = self.pos_embedding_layer(torch.arange(seq_length))
        pos_embeddings = pos_embeddings.unsqueeze(0).repeat(batch_size, 1, 1)
        input_embeddings = token_embeddings + pos_embeddings
        transformer_out = self.transformer(input_embeddings, input_embeddings)
        logits = self.linear(transformer_out)
        return logits

    def train_model(self, train_dataloader, num_epochs, learning_rate, save_path):
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(self.parameters(), lr=learning_rate)

        for epoch in range(num_epochs):
            total_loss = 0
            for inputs, targets in train_dataloader:
                optimizer.zero_grad()
                logits = self.forward(inputs)
                loss = criterion(logits.view(-1, logits.size(-1)), targets.view(-1))
                loss.backward()
                optimizer.step()
                total_loss += loss.item()

            print(f"Epoch {epoch+1}/{num_epochs}, Loss: {total_loss:.4f}")

            # Save the model after training
            # Save every 4 iterations of epoch
            if epoch == range(num_epochs)[-1]:
                torch.save(self.state_dict(), save_path)
                print(f"Model final saved to {save_path}")
            elif (epoch + 1) % 4 == 0:
                torch.save(self.state_dict(), save_path)
                print(f"Model checkpoint saved to {save_path}")
            

Using device: cuda


In [78]:
with open("data/genesis.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

dataloader = create_dataloader(raw_text, batch_size=16, max_length=8, stride=9)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[13746,  9339,   352,    25,    16,   197,   818,   262],
        [ 1793,  2727,   262, 27636,   290,   262,  4534,    13],
        [13746,  9339,   352,    25,    17,   197,  3844,   262],
        [  373,  1296,  1203,   290,  7951,    11,   290, 11854],
        [  625,   262,  4417,   286,   262,  2769,    13,   843],
        [ 7710,   286,  1793,   373, 33627,   625,   262,  4417],
        [  262, 10150,    13,   198, 13746,  9339,   352,    25],
        [  197,  1870,  1793,   531,    11,   564,   250,  5756],
        [  307,  1657,    11,   447,   251,   290,   612,   373],
        [   13,   198, 13746,  9339,   352,    25,    19,   197],
        [ 1793,  2497,   326,   262,  1657,   373,   922,    11],
        [  679, 11266,   262,  1657,   422,   262, 11854,    13],
        [13746,  9339,   352,    25,    20,   197, 13482,  1444],
        [ 1657,   564,   250,   820,    11,   447,   251,   290],
        [11854,   679,  1444,   564,   250,  3847,    13,   447],
 

In [79]:
model = GPT1(vocab_size=vocab_size, output_dim=output_dim, block_size=8, num_heads=4, num_layers=8)

In [80]:
model.train_model(dataloader, num_epochs=64, learning_rate=0.01, save_path="models/gpt1.pth")

Epoch 1/64, Loss: 2591.8712
Epoch 2/64, Loss: 2302.6917
Epoch 3/64, Loss: 2292.9683
Epoch 4/64, Loss: 2278.7098
Model checkpoint saved to models/gpt1.pth
Epoch 5/64, Loss: 2272.9229
Epoch 6/64, Loss: 2262.0663
Epoch 7/64, Loss: 2257.1646
Epoch 8/64, Loss: 2251.5147
Model checkpoint saved to models/gpt1.pth
Epoch 9/64, Loss: 2246.3685
Epoch 10/64, Loss: 2242.5560
Epoch 11/64, Loss: 2240.2304
Epoch 12/64, Loss: 2238.2234
Model checkpoint saved to models/gpt1.pth
Epoch 13/64, Loss: 2237.8613
Epoch 14/64, Loss: 2237.5413
Epoch 15/64, Loss: 2237.5865
Epoch 16/64, Loss: 2235.4168
Model checkpoint saved to models/gpt1.pth


KeyboardInterrupt: 

In [81]:
# Load the trained model
# model = GPT1(vocab_size=vocab_size, output_dim=output_dim, block_size=5, num_heads=2, num_layers=2)
model.load_state_dict(torch.load("models/gpt1.pth"))

# Set the model to evaluation mode
model.eval()

GPT1(
  (token_embedding_layer): Embedding(50257, 256)
  (pos_embedding_layer): Embedding(8, 256)
  (transformer): Transformer(
    (encoder): TransformerEncoder(
      (layers): ModuleList(
        (0-7): 8 x TransformerEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
          )
          (linear1): Linear(in_features=256, out_features=2048, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (linear2): Linear(in_features=2048, out_features=256, bias=True)
          (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (dropout1): Dropout(p=0.1, inplace=False)
          (dropout2): Dropout(p=0.1, inplace=False)
        )
      )
      (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): TransformerDecoder(
      (layers): ModuleList(
  

In [88]:

# Generate text using the trained model
text = "Genesis 1:31"
input_ids = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(input_ids)
# input_ids_trunc = input_ids[:32]
input_ids_trunc = input_ids + [50256] * (8 - len(input_ids))
print(input_ids_trunc)
input_tensor = torch.tensor(input_ids_trunc).unsqueeze(0)
with torch.no_grad():
    output = model(input_tensor)
    print(output)
    predicted_token_ids = torch.argmax(output, dim=-1)
    print(predicted_token_ids)
    tokenizer = tiktoken.get_encoding("gpt2")
    predicted_text = tokenizer.decode(predicted_token_ids.squeeze().tolist())
    # Print the generated text
    print(predicted_text)


[13746, 9339, 352, 25, 3132]
[13746, 9339, 352, 25, 3132, 50256, 50256, 50256]
tensor([[[  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         ...,
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736]]])
tensor([[262, 262, 262, 262, 262, 262, 262, 262]])
 the the the the the the the the


In [99]:
output

tensor([[[  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         ...,
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736],
         [  1.5669, -11.3029, -11.0016,  ..., -11.2498, -11.9219, -11.9736]]])

In [101]:
output.size()

torch.Size([1, 8, 50257])

In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")
tokenizer.decode([11])

','

#### Debug
Count most common tokens

In [64]:
with open("data/genesis.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

print(tokenizer.encode(raw_text))

# Count elements of list and sort descending by frequency
from collections import Counter
counter = Counter(tokenizer.encode(raw_text))
print(counter.most_common(10))

[13746, 9339, 352, 25, 16, 197, 818, 262, 3726, 1793, 2727, 262, 27636, 290, 262, 4534, 13, 198, 13746, 9339, 352, 25, 17, 197, 3844, 262, 4534, 373, 1296, 1203, 290, 7951, 11, 290, 11854, 373, 625, 262, 4417, 286, 262, 2769, 13, 843, 262, 7710, 286, 1793, 373, 33627, 625, 262, 4417, 286, 262, 10150, 13, 198, 13746, 9339, 352, 25, 18, 197, 1870, 1793, 531, 11, 564, 250, 5756, 612, 307, 1657, 11, 447, 251, 290, 612, 373, 1657, 13, 198, 13746, 9339, 352, 25, 19, 197, 1870, 1793, 2497, 326, 262, 1657, 373, 922, 11, 290, 679, 11266, 262, 1657, 422, 262, 11854, 13, 198, 13746, 9339, 352, 25, 20, 197, 13482, 1444, 262, 1657, 564, 250, 820, 11, 447, 251, 290, 262, 11854, 679, 1444, 564, 250, 3847, 13, 447, 251, 843, 612, 373, 6180, 11, 290, 612, 373, 3329, 960, 1169, 717, 1110, 13, 198, 13746, 9339, 352, 25, 21, 197, 1870, 1793, 531, 11, 564, 250, 5756, 612, 307, 281, 1033, 40054, 1022, 262, 10150, 11, 284, 4553, 262, 10150, 422, 262, 10150, 13, 447, 251, 198, 13746, 9339, 352, 25, 22, 197, 2

In [65]:
tokenizer.decode([262])

' the'